# Trivy CVE suppressions (YAML format — supports path-specific ignores)
# See: https://trivy.dev/docs/latest/configuration/filtering/
#
# To suppress a CVE globally:
#   - id: CVE-2024-XXXXX
#     statement: "no fix available in base image"
#
# To suppress a CVE in a specific file only:
#   - id: CVE-2024-XXXXX
#     paths:
#       - path/to/requirements.txt
#     statement: "pinned for compatibility; upgrade tracked in SCOUT-XXX"

vulnerabilities:
  - id: CVE-2025-32434
    paths:
      - helm/jupyter/embedding-notebook/requirements.txt
    statement: 'torch pinned at 2.0.1 for embedding notebook compatibility; upgrade to 2.6.0 pending validation'
