---
server:
  hosts:
    HOSTNAME:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      k3s_control_node: true
minio_hosts:
  children:
    server:
k3s_cluster:
  children:
    server:
  vars:
    hl7log_extractor_image_repository: docker.io/local/washu-tag/hl7log-extractor
    hl7_transformer_image_repository: docker.io/local/washu-tag/hl7-transformer
    launchpad_image_repository: docker.io/local/washu-tag/launchpad

    # K3s config
    k3s_token: K3S_TOKEN
    kubeconfig_group: root

    # OIDC config
    minio_oidc_enabled: false
    temporal_oidc_enabled: false

    # Minio config, ensure passwords meet complexity requirements (must be >=8 characters)
    minio_storage_size: 5Gi
    minio_volumes_per_server: 1
    s3_username: minio
    s3_password: minio123
    s3_region: us-east-1
    s3_lake_reader: lake-reader
    s3_lake_reader_secret: lakereader123
    s3_lake_writer: lake-writer
    s3_lake_writer_secret: lakewriter123
    s3_loki_writer: loki-writer
    s3_loki_writer_secret: lokiwriter123

    # Monitor config
    prometheus_storage_size: 1Gi
    loki_storage_size: 1Gi
    grafana_storage_size: 1Gi

    # Jupyter config
    jupyter_hub_storage_size: 1Gi
    jupyter_singleuser_storage_size: 1Gi

    # Postgres config
    postgres_user: scout
    postgres_password: scout123
    postgres_superuser_password: scout123
    hive_postgres_user: hive
    hive_postgres_password: hive123
    hive_readonly_postgres_password: hivero123
    superset_postgres_user: superset
    superset_postgres_password: superset123
    postgres_resources: {} # No resource requests/limits
    postgres_parameters: {} # Use PG defaults
    postgres_storage_size: 5Gi

    # Orchestrator config
    cassandra_storage_size: 1Gi
    elasticsearch_storage_size: 1Gi

    # Local paths
    base_dir: /var/lib
    scout_repo_dir: WORK_DIR
    minio_dir: '{{ base_dir }}/minio'
    cassandra_dir: '{{ base_dir }}/cassandra'
    elasticsearch_dir: '{{ base_dir }}/elasticsearch'
    postgres_dir: '{{ base_dir }}/postgres'
    prometheus_dir: '{{ base_dir }}/prometheus'
    loki_dir: '{{ base_dir }}/loki'
    grafana_dir: '{{ base_dir }}/grafana'
    jupyter_dir: '{{ base_dir }}/jupyter'
    extractor_data_dir: '{{ scout_repo_dir }}/tests/ingest/staging_test_data'

    # Object storage paths
    lake_bucket: ci-lake
    scratch_bucket: ci-scratch

    # Resources
    hl7_transformer_spark_memory: 1G
    cassandra_init_heap: 1G
    cassandra_max_heap: 1G
