# SECURITY SCAN TEST — DELETE THIS DIRECTORY AFTER VERIFYING SCANNERS
# This file should be flagged by Semgrep (p/secrets)

AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
